import { getAllStudents } from '../helpers/get-all-students';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home({ students }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {students.length === 0 ? (
          <div className="load-students-div"></div>
        ) : (
          <div className="load-students-div">
            <label>Select a Students Name then Click "Load Data": </label>
            {/* <select
              value={students?.findIndex(
                (obj) => obj.studentId === selectedStudent.studentId,
              )}
              onChange={(e) => setSelectedStudent(students[e.target.value])}
            > */}
              {students.map((obj, ndx) => (
                <option key={obj.studentId} value={ndx}>
                  {obj.studentName}
                </option>
              ))}
            </select>
            {/* <button onClick={loadData}>Load Data</button> */}
          </div>
        )}

        {/* <h1>List of Students</h1>
        {students.map((student) => {
          return <div key={student.studentId}>{student.studentName}</div>;
        })} */}
      </main>

      <footer className={styles.footer}>footer</footer>
    </div>
  );
}

export async function getServerSideProps() {
  const allStudents = await getAllStudents();

  return {
    props: {
      students: allStudents,
    },
  };
}
